name: Update Latest Blog Posts

on:
  schedule:
    - cron: '0 1/2 * * *'
  workflow_dispatch:
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          max_post_count: 20
          feed_list: "https://jasontucker.blog/feed/,https://wpwatercooler.com/wpwatercooler/feed/"
          feed_names: "Jason Tucker,WPwatercooler Show"
          template: "<tr><td>$randomEmoji(💯,🔥,💫,🚀,🌮) $title</td><td>$url - <em>$feedName</em></td></tr>"